[tool.pytest.ini_options]
addopts = "--strict-markers --cov aiostream"

[tool.pyright]
strict = []

[tool.mypy]
packages = ["aiostream", "examples"]

[tool.mypy-aiostream]
strict = true

[tool.mypy-examples]
strict = true

[tool.black]
line-length = 88
target_version = ["py38", "py39", "py310", "py311", "py312"]

[tool.coverage.report]
exclude_also = ["if TYPE_CHECKING:", "assert False"]

[tool.ruff]
ignore = ["E501", "F403"]
